### ISSUE TITLE
Tests fail on all platforms except MacOSX

### ISSUE THREAD

**Issue by eserte** [mcmillhj/App-Highlander#1] opened 2015-11-28 20:49 UTC
See http://matrix.cpantesters.org/?dist=App-Highlander%200.002 for a pass/fail overview --- currently there's only a pass report on a MacOSX system, everything else are fails.

**Comment by mcmillhj** [comment] 2015-11-28 22:39
Hi @eserte, 

Thanks for reporting this issue, I have been receiving the failures and trying to work out a solution locally. I believe the cause is that by default this application attempts to write to a directory in `/var` which is likely restricted in many tester environments. 

Should have a solution soon.

**Comment by mcmillhj** [comment] 2015-11-30 22:35
Resolved by 3c5d261937db0593b05ac00e688eca29611e7a70

**Closed as completed by mcmillhj** 2015-11-30 22:35 UTC
